JoinColony/block-ingestor

- src/eventProcessor.ts
- src/handlers/actions/index.ts
- src/handlers/actions/unlockToken.ts
- src/types.ts
- src/utils/actions/listener.ts
This is a parallel PR to CDapp's https://github.com/JoinColony/colonyCDapp/pull/290
Please refer to that PR for testing instructions
> Add support for UnlockToken action

- src/eventProcessor.ts
- src/handlers/actions/editColony.ts
- src/handlers/actions/index.ts
- src/types.ts
- src/utils/actions/listener.ts
I accidentally closed the other PR without merging and can't reopen it: #26
> Add Colony Edit action handler

- src/amplifyClient.ts
- src/eventListener.ts
- src/eventProcessor.ts
- src/handlers/motions/index.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionVoteSubmitted/helpers.ts
- src/handlers/motions/motionVoteSubmitted/index.ts
- src/types/index.ts
- src/types/motions.ts
This PR adds support for the `MotionVoteSubmitted` event (i.e. motion voting).
Test with: https://github.com/JoinColony/colonyCDapp/pull/380
> Add voting support (motions)

- src/eventListener.ts
- src/eventProcessor.ts
- src/handlers/motions/index.ts
- src/handlers/motions/motionVoteRevealed/index.ts
- src/handlers/motions/motionVoteSubmitted/helpers.ts
- src/types/index.ts
- src/types/motions.ts
This PR adds support for the Reveal widget. Test with https://github.com/JoinColony/colonyCDapp/pull/385
> Add reveal support

- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/unlockToken.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/index.ts
- src/types/motions.ts
This PR adds support for the Unlock Token motion. Test with https://github.com/JoinColony/colonyCDapp/pull/429
> Add UnlockTokenMotion support

- src/eventProcessor.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/index.ts
- src/types/motions.ts
- src/utils/domains.ts
This PR should support creating motions that add or edit domains by storing them in the DB.
CDapp counterpart: https://github.com/JoinColony/colonyCDapp/pull/379
> Add support for Create/Edit Domain motions

- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/payment.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/index.ts
- src/types/motions.ts
This pr adds support for the payment motion. Test with: https://github.com/JoinColony/colonyCDapp/pull/430/
> Add payment motion support

- src/amplifyClient.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionStaked/helpers.ts
- src/handlers/motions/motionStaked/motionStaked.ts
- src/types/motions.ts
This PR:
- adds events to motion data
- creates an event when a motion is created
- creates an event when a motion is staked
> Define events for motion data

- src/handlers/motions/motionStaked/helpers.ts
- src/types/motions.ts
This pr adds support for displaying the voting message in motions. Test with: joinColony/colonyCDapp#459
> Wire voting message

- src/eventQueue.ts
Currently, the block ingestor processes events concurrently. I.e. It doesn't wait for Event 1 to finish before processing Event 2. 
This is a problem in the case that two events depend on the same state. Event 2 will overwrite the changes made by Event 1. 
This PR makes the eventQueue wait for each event to finish being processed before it starts processing another. I have tested with https://github.com/JoinColony/block-ingestor/pull/82, and haven't noticed any problems. 
I recommend testing via that pr also. All events should be handled as expected (basically as before, but sequential).
Two users claim their stakes on the same motion at the same time.
Both claims are processed with the current state of the motion, which is:
User 1 claimed: false,
User 2 claimed: false
User 1's claim is …
> Refactor event queue to run in sequence

- src/handlers/motions/motionFinalized/helpers.ts
Instructions to test are in https://github.com/JoinColony/colonyCDapp/pull/627
> Filter out 0 colony claims

- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/setUserRoles.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/events.ts
- src/types/motions.ts
- src/utils/permissions.ts
Test instructions included in the CDapp counterpart: https://github.com/JoinColony/colonyCDapp/pull/629
> Add handler for permission management motion

- src/handlers/motions/motionStaked/helpers.ts
This fixes an issue that was causes by #91 that undid a fix in #69
This adds back the fix for rounding up to one for wrong stake side.
> Fix: rounding wrong side

- package-lock.json
- package.json
- src/eventListeners/colony.ts
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/graphql/mutations/expenditures.graphql
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/expenditureAdded.ts
- src/handlers/expenditures/expenditureCancelled.ts
- src/handlers/expenditures/expenditureClaimDelaySet.ts
- src/handlers/expenditures/expenditureFinalized.ts
- src/handlers/expenditures/expenditureGlobalClaimDelaySet.ts
- src/handlers/expenditures/expenditureLocked.ts
- src/handlers/expenditures/expenditurePayoutModifierSet.ts
- src/handlers/expenditures/expenditurePayoutSet.ts
- src/handlers/expenditures/expenditureRecipientSet.ts
- src/handlers/expenditures/expenditureTransferred.ts
- src/handlers/expenditures/helpers/getExpenditure.ts
- src/handlers/expenditures/helpers/index.ts
- src/handlers/expenditures/index.ts
- src/handlers/index.ts
- src/handlers/motions/helpers.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/handlers/motions/motionRewardClaimed/helpers.ts
- src/types/events.ts
- src/utils/colonyClient.ts
- src/utils/expenditures.ts
- src/utils/index.ts
This PR delivers the Milestone 1 of Advanced Payments project: Handling expenditures events.
> Advanced Payments Milestone 1: Handling expenditures events

- src/eventListeners/colony.ts
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/graphql/queries/actions.graphql
- src/handlers/actions/annotateTransaction.ts
- src/handlers/actions/index.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/types/events.ts
This PR adds annotations support to the block ingestor.
Test with: https://github.com/JoinColony/colonyCDapp/pull/909
> Add annotations support

- src/constants.ts
- src/graphql/fragments/motions.graphql
- src/graphql/generated.ts
- src/graphql/mutations/decisions.graphql
- src/graphql/mutations/motions.graphql
- src/graphql/queries/decisions.graphql
- src/graphql/queries/motions.graphql
- src/handlers/actions/annotateTransaction.ts
- src/handlers/motions/helpers.ts
- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/simpleDecision.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/motions.ts
- src/utils/decisions.ts
This PR provides decisions support in the block-ingestor.
> Add simple decisions support

- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/expenditureAdded.ts
- src/handlers/expenditures/helpers/getExpenditureFundingPotId.ts
- src/handlers/expenditures/helpers/index.ts
- src/types/events.ts
- src/utils/actions/writeAction.ts
block-ingestor counterpart of [colonyCDapp#906](https://github.com/JoinColony/colonyCDapp/pull/906)
> Funding an expenditure

- codegen.ts
- package-lock.json
- package.json
- src/graphql/generated.ts
- src/handlers/expenditures/expenditureFinalized.ts
block-ingestor counterpart of https://github.com/JoinColony/colonyCDapp/pull/925
> Claiming expenditure payout

- .husky/pre-commit
- src/constants.ts
- src/eventListeners/extensions.ts
- src/eventListeners/index.ts
- src/eventListeners/stakedExpenditure.ts
- src/eventListeners/types.ts
- src/graphql/generated.ts
- src/handlers/extensions/extensionInitialised.ts
- src/handlers/extensions/extensionInstalled.ts
- src/handlers/extensions/extensionUninstalled.ts
- src/interfaces.ts
- src/types/motions.ts
- src/utils/clients/index.ts
- src/utils/clients/stakedExpenditure.ts
- src/utils/extensions/index.ts
- src/utils/extensions/stakedExpenditure.ts
- src/utils/extensions/votingRep.ts
block-ingestor counterpart of [colonyCDapp#950](https://github.com/JoinColony/colonyCDapp/pull/950)
> Installing and initializing Staked Expenditure extension

- package-lock.json
- package.json
- src/constants.ts
block-ingestor counterpart of [colonyCDapp#1026](https://github.com/JoinColony/colonyCDapp/pull/1026).
> Staged Expenditure extension support

- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/expenditurePayoutClaimed.ts
- src/handlers/expenditures/expenditurePayoutSet.ts
- src/interfaces.ts
https://github.com/JoinColony/colonyCDapp/pull/1036
> Cache expenditure payout claimed status

- src/amplifyClient.ts
- src/graphql/fragments/motions.graphql
- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/motions/motionCreated/handlers/editColony.ts
- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/manageDomain.ts
- src/handlers/motions/motionCreated/handlers/mintTokens.ts
- src/handlers/motions/motionCreated/handlers/moveFunds.ts
- src/handlers/motions/motionCreated/handlers/multicall/fragments.ts
- src/handlers/motions/motionCreated/handlers/multicall/index.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicall.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/index.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/moveFundsBetweenPots.ts
- src/handlers/motions/motionCreated/handlers/networkUpgrade.ts
- src/handlers/motions/motionCreated/handlers/payment.ts
- src/handlers/motions/motionCreated/handlers/reputation.ts
- src/handlers/motions/motionCreated/handlers/setUserRoles.ts
- src/handlers/motions/motionCreated/handlers/unlockToken.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/motions.ts
- src/utils/actions/writeAction.ts
Support for motion funding in block ingestor.
> Expenditure Fund Motion support

- package-lock.json
- package.json
- src/eventListeners/extension/stakedExpenditure.ts
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/handlers/expenditures/expenditureCancelled.ts
- src/handlers/expenditures/expenditureStakerPunished.ts
- src/handlers/expenditures/helpers/index.ts
- src/handlers/expenditures/helpers/updateCancelledExpenditure.ts
- src/handlers/expenditures/index.ts
- src/handlers/expenditures/stakedExpenditureCancelled.ts
- src/handlers/extensions/extensionInitialised.ts
- src/types/events.ts
[colonyCDapp#1059](https://github.com/JoinColony/colonyCDapp/pull/1059)
> Cancelling staked expenditure

- src/graphql/generated.ts
- src/graphql/mutations/extension.graphql
- src/graphql/queries/extensions.graphql
- src/handlers/extensions/extensionDeprecated.ts
- src/handlers/extensions/extensionUpgraded.ts
- src/utils/extensions/writeExtension.ts
Moved `updatedExtensionByColonyAndHash` lambda function logic to the block-ingestor as it's only used here.
Resolves [colonyCDapp#339](https://github.com/JoinColony/colonyCDapp/issues/339)
> Move `updateExtensionByColonyAndHash` lamda to block ingestor

- src/handlers/actions/managePermissions.ts
This is a bug fix as identified here: https://github.com/JoinColony/colonyCDapp/issues/1008
I believe it's caused by setting the recovery role. The recovery role event is handled by the same handler as all other roles, but it has a different event signature: specifically, it doesn't include the `msg.sender`. We were using this as the `initiatorAddress` on the action, but since that field is non-nullable, the mutation fails. 
Confirm you're not experiencing the same issues as colonyCDapp#1008 and that the action is created for all permutations of setting permissions.
Resolves  https://github.com/JoinColony/colonyCDapp/issues/1008
> Add initiator address fallback for recovery action

- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/motions/motionCreated/handlers/expenditures/cancelStakedExpenditures.ts
- src/handlers/motions/motionCreated/handlers/expenditures/index.ts
- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/moveFundsBetweenPots.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/motions.ts
https://github.com/JoinColony/colonyCDapp/pull/1087
> Cancel stake motion

- src/constants.ts
- src/eventListeners/extension/index.ts
- src/eventListeners/extension/stakedExpenditure.ts
- src/eventListeners/extension/streamingPayments.ts
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/graphql/mutations/expenditures.graphql
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/expenditureAdded.ts
- src/handlers/expenditures/expenditureMadeStaged.ts
- src/handlers/expenditures/expenditureMadeViaStake.ts
- src/handlers/expenditures/helpers/getExpenditure.ts
- src/handlers/expenditures/index.ts
- src/handlers/expenditures/paymentTokenUpdated.ts
- src/handlers/expenditures/streamingPaymentCreated.ts
- src/handlers/extensions/extensionInstalled.ts
- src/handlers/motions/motionCreated/handlers/expenditures/cancelStakedExpenditures.ts
- src/handlers/motions/motionCreated/handlers/expenditures/index.ts
- src/handlers/motions/motionCreated/handlers/index.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/moveFundsBetweenPots.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/interfaces.ts
- src/types/events.ts
- src/types/motions.ts
- src/utils/clients/index.ts
- src/utils/clients/streamingPayments.ts
https://github.com/JoinColony/colonyCDapp/pull/1068
> Advanced Payments API - Phase 2

- src/graphql/generated.ts
- src/graphql/queries/extensions.graphql
- src/handlers/actions/mintTokens.ts
- src/handlers/actions/oneTxPayment.ts
- src/handlers/colonies/transfer.ts
- src/handlers/expenditures/expenditurePayoutClaimed.ts
- src/utils/actions/writeAction.ts
- src/utils/fundsClaims.ts
- src/utils/index.ts
- src/utils/isColonyAddress.ts
This resolves https://github.com/JoinColony/colonyCDapp/issues/991 which is needed to display the Payment actions fund claims after contracts update.
For testing, create a payment action with a colony as a recipient and confirm the incoming funds are showing up.
> Show Payment actions incoming funds

- src/graphql/fragments/motions.graphql
- src/graphql/generated.ts
- src/graphql/index.ts
- src/graphql/mutations/stake.graphql
- src/graphql/queries/stake.graphql
- src/handlers/motions/motionRewardClaimed/helpers.ts
- src/handlers/motions/motionRewardClaimed/motionRewardClaimed.ts
- src/handlers/motions/motionStaked/helpers.ts
- src/handlers/motions/motionStaked/motionStaked.ts
- src/utils/stakes.ts
https://github.com/JoinColony/colonyCDapp/pull/1246
> User Hub - Stakes tab

- src/graphql/generated.ts
- src/handlers/actions/oneTxPayment.ts
- src/handlers/expenditures/expenditurePayoutSet.ts
- src/utils/networkFee.ts
https://github.com/JoinColony/colonyCDapp/pull/1912
> Include network fee when setting advanced payments payouts

- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/actions/moveFunds.ts
- src/handlers/expenditures/expenditureAdded.ts
- src/handlers/expenditures/expenditurePayoutClaimed.ts
- src/utils/expenditures.ts
- src/utils/networkFee.ts
https://github.com/JoinColony/colonyCDapp/pull/1918
> Colony balance should include funds currently in expenditures' pots

- src/graphql/generated.ts
- src/handlers/motions/motionCreated/handlers/multicall/fragments.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/index.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/setExpenditureState.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/handlers/motions/motionFinalized/motionFinalized.ts
- src/types/motions.ts
- src/utils/clients/index.ts
- src/utils/clients/stagedExpenditure.ts
See https://github.com/JoinColony/colonyCDapp/pull/1984
> Feat: Motion handler for release expenditure stage

- src/graphql/generated.ts
- src/handlers/expenditures/expenditureClaimDelaySet.ts
- src/handlers/expenditures/expenditureGlobalClaimDelaySet.ts
- src/handlers/expenditures/helpers/decodeSetExpenditureState.ts
https://github.com/JoinColony/colonyCDapp/pull/2022
> Fix: claim delay being stored as `Int` causes overflow

- src/eventListeners/colony.ts
- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/graphql/mutations/expenditures.graphql
- src/handlers/actions/editDomain.ts
- src/handlers/actions/moveFunds.ts
- src/handlers/expenditures/expenditureAdded.ts
- src/handlers/expenditures/expenditureMadeViaStake.ts
- src/handlers/expenditures/helpers/updateExpenditureStake.ts
- src/types/events.ts
- src/utils/index.ts
- src/utils/transactionHasEvent.ts
https://github.com/JoinColony/colonyCDapp/pull/1969/
> Connect expenditures with actions model

- src/graphql/generated.ts
- src/handlers/motions/motionCreated/handlers/expenditures/cancelExpenditureViaArbitration.ts
- src/handlers/motions/motionCreated/handlers/expenditures/index.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/motions.ts
https://github.com/JoinColony/colonyCDapp/pull/2020
> Cancelling non-staked expenditure as non-owner (using motions)

- src/graphql/generated.ts
- src/handlers/expenditures/expenditureFinalized.ts
https://github.com/JoinColony/colonyCDapp/pull/2099
> Return info about expenditure Release action

- src/graphql/generated.ts
- src/handlers/motions/motionCreated/handlers/expenditures/finalizeExpenditureViaArbitration.ts
- src/handlers/motions/motionCreated/handlers/expenditures/index.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/motions.ts
https://github.com/JoinColony/colonyCDapp/pull/2097
> Finalizing expenditure as non-owner (using motions)

- src/graphql/generated.ts
- src/handlers/actions/emitDomainReputation.ts
- src/handlers/expenditures/expenditureCancelled.ts
- src/handlers/expenditures/helpers/getExpenditure.ts
- src/utils/actions/writeAction.ts
https://github.com/JoinColony/colonyCDapp/pull/2132
> Advanced Payments API: Return info about Cancel action

- src/graphql/generated.ts
- src/graphql/mutations/currentVersion.graphql
- src/graphql/queries/currentVersion.graphql
- src/handlers/colonies/colonyVersionAdded.ts
- src/utils/currentVersion.ts
- src/utils/extensions/writeExtension.ts
- src/utils/seedDB.ts
https://github.com/JoinColony/colonyCDapp/pull/2162
> Fix: incorrect latest colony version in the DB

- src/graphql/generated.ts
- src/graphql/mutations/currentVersion.graphql
- src/graphql/queries/currentVersion.graphql
- src/handlers/colonies/colonyVersionAdded.ts
- src/utils/currentVersion.ts
- src/utils/extensions/writeExtension.ts
- src/utils/seedDB.ts
This PR applies fix from #197 to `master-arbitrum` branch.
> Fix: Incorrect colony version (Arbitrum deployment)

- src/graphql/generated.ts
- src/graphql/mutations/colony.graphql
- src/graphql/mutations/contributors.graphql
- src/graphql/mutations/currentVersion.graphql
- src/graphql/queries/colony.graphql
- src/graphql/queries/currentVersion.graphql
- src/handlers/colonies/colonyAdded.ts
- src/handlers/colonies/colonyVersionAdded.ts
- src/handlers/colonies/helpers/createUniqueColony.ts
- src/utils/currentVersion.ts
- src/utils/extensions/writeExtension.ts
- src/utils/seedDB.ts
Please see CDapp counterpart for details: https://github.com/JoinColony/colonyCDapp/pull/2225
> Fix: Colony creation failure handling

- package-lock.json
- package.json
- src/eventListeners/extension/streamingPayments.ts
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/index.ts
- src/handlers/expenditures/streamingPaymentEndTimeSet.ts
- src/handlers/tokens/setTokenAuthority.ts
- src/types/events.ts
[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2321)
> Feat: Cancel streams using permissions

- src/handlers/motions/motionCreated/motionCreated.ts
- src/provider.ts
[CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2356)
> Fix: Use StaticJsonRpcProvider where appropriate

- src/graphql/generated.ts
- src/handlers/expenditures/stagedPaymentReleased.ts
- src/handlers/motions/motionCreated/handlers/expenditures/index.ts
- src/handlers/motions/motionCreated/handlers/expenditures/releaseStagedPaymentViaArbitration.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/types/motions.ts
[Please see CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2392)
This PR introduces a `releaseStagedPaymentViaArbitration` handler.
> Fix: Release expenditure stage via motion

- package-lock.json
- package.json
- src/constants.ts
- src/eventListeners/extension/index.ts
- src/eventListeners/extension/multiSig.ts
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/handlers/extensions/extensionInstalled.ts
- src/handlers/multiSig/globalThresholdUpdated/index.ts
- src/handlers/multiSig/index.ts
- src/interfaces.ts
- src/types/events.ts
- src/utils/clients/voting.ts
- src/utils/events.ts
- src/utils/extensions/multiSig.ts
[The CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2229)
> [Multi-sig] feat: implement installation and global configuration of the multi-sig extension

- src/eventProcessor.ts
- src/graphql/generated.ts
- src/handlers/actions/managePermissions.ts
- src/handlers/motions/motionCreated/handlers/setUserRoles.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/utils/permissions.ts
[CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2294)
> [Multi-sig] Update manage permissions handler to handle MultiSigRoleSet

- src/eventProcessor.ts
- src/graphql/fragments/multiSig.graphql
- src/graphql/generated.ts
- src/graphql/index.ts
- src/graphql/mutations/multiSig.graphql
- src/graphql/queries/domain.graphql
- src/graphql/queries/multiSig.graphql
- src/handlers/multiSig/helpers.ts
- src/handlers/multiSig/index.ts
- src/handlers/multiSig/multiSigCreated/handlers/mintTokens.ts
- src/handlers/multiSig/multiSigCreated/helpers.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
- src/types/motions.ts
[This CDApp PR](https://github.com/JoinColony/colonyCDapp/pull/2270)
> [Multi-sig] feat: implement multiSig motion creation

- package-lock.json
- src/eventProcessor.ts
- src/graphql/generated.ts
- src/graphql/queries/domain.graphql
- src/graphql/queries/extensions.graphql
- src/handlers/index.ts
- src/handlers/multiSig/domainSkillThresholdSet.ts
- src/handlers/multiSig/globalThresholdSet.ts
- src/handlers/multiSig/index.ts
[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2253)
This PR adds a handler for the `DomainSkillThresholdSet`. It also adjusts the `setGlobalThreshold` handler to ensure it does not override the domain thresholds.
> Added handler for domainSkillThresholdSet event

- src/graphql/fragments/colony.graphql
- src/graphql/fragments/token.graphql
- src/graphql/generated.ts
- src/handlers/metadataDelta/handlers/manageTokens.ts
- src/handlers/metadataDelta/metadataDelta.ts
- src/utils/metadataDelta/types.ts
- src/utils/metadataDelta/utils.ts
- src/utils/tokens.ts
See CDapp counterpart for details
> [Manage Tokens] Feat: Implement `manageTokens metadataDelta` handler

- src/graphql/generated.ts
- src/handlers/metadataDelta/handlers/manageTokens.ts
[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2476)
> [Manage Tokens] Feat: Add token changes to colony action

- src/graphql/fragments/colony.graphql
- src/graphql/generated.ts
- src/handlers/metadataDelta/handlers/manageTokens.ts
- src/handlers/motions/motionCreated/handlers/metadataDelta.ts
- src/handlers/motions/motionCreated/handlers/metadataDeltaHandlers/manageTokens.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/utils/tokens.ts
[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2480)
> [Manage Tokens] Feat: Handle manageTokens metadataDelta motion

- src/handlers/multiSig/multiSigCreated/handlers/index.ts
- src/handlers/multiSig/multiSigCreated/handlers/unlockToken.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
Implement unlock token multi-sig motion.
Part of https://github.com/JoinColony/colonyCDapp/pull/2578
> Implement unlock token multi-sig motion

- src/graphql/fragments/multiSig.graphql
- src/graphql/generated.ts
- src/handlers/multiSig/index.ts
- src/handlers/multiSig/multiSigCancelled.ts
- src/handlers/multiSig/multiSigExecuted/multiSigExecuted.ts
Added information about rejection time, rejector user and executor user for multi-sig 
Renamed motionCancelled to multiSigCancelled
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2579)
> Feat: add rejectedAt, rejectedBy and executedBy for ColonyMultiSig

- src/handlers/multiSig/multiSigCreated/handlers/addDomain.ts
- src/handlers/multiSig/multiSigCreated/handlers/addOrEditDomain.ts
- src/handlers/multiSig/multiSigCreated/handlers/index.ts
- src/handlers/multiSig/multiSigCreated/helpers.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
- src/handlers/multiSig/multiSigExecuted/multiSigExecuted.ts
- src/utils/colonyMetadata.ts
This is needed to test [colonyCDapp#2588: Feat: enable addDomain multi-sig flow](https://github.com/JoinColony/colonyCDapp/pull/2588)
> Feat: Handle both addDomain and editDomain actions created via a Multi-Sig decision method

- src/handlers/multiSig/multiSigCreated/handlers/index.ts
- src/handlers/multiSig/multiSigCreated/handlers/moveFunds.ts
- src/handlers/multiSig/multiSigCreated/helpers.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
Part of: https://github.com/JoinColony/colonyCDapp/pull/2657
> Add move funds multisig handler

- src/graphql/generated.ts
- src/graphql/queries/multiSig.graphql
- src/handlers/multiSig/approvalChanged/approvalChanged.ts
- src/handlers/multiSig/helpers.ts
- src/handlers/multiSig/multiSigCreated/handlers/payment.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
- src/handlers/multiSig/rejectionChanged/rejectionChanged.ts
[CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2641)
> [Multi-sig] feat: handle simple payment multisig

- src/handlers/multiSig/multiSigCreated/handlers/index.ts
- src/handlers/multiSig/multiSigCreated/handlers/manageReputation.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
Part of [this](https://github.com/JoinColony/colonyCDapp/pull/2697) CDapp PR.
> Feat: Manage Reputation Multi-Sig Handler

- src/handlers/multiSig/multiSigCreated/handlers/colonyVersionUpgrade.ts
- src/handlers/multiSig/multiSigCreated/handlers/index.ts
- src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
Please use this to test [colonyCDapp#2696 - Feat: Upgrade Colony version via Multi-Sig](https://github.com/JoinColony/colonyCDapp/pull/2696)
> Feat: Enable Colony version upgrade via a multi-sig motion

- package-lock.json
- package.json
- src/graphql/fragments/colony.graphql
- src/graphql/fragments/token.graphql
- src/graphql/generated.ts
- src/handlers/metadataDelta/handlers/manageTokens.ts
- src/handlers/metadataDelta/metadataDelta.ts
- src/handlers/motions/motionCreated/handlers/metadataDelta.ts
- src/handlers/motions/motionCreated/handlers/metadataDeltaHandlers/manageTokens.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/handlers/tokens/setTokenAuthority.ts
- src/utils/metadataDelta/types.ts
- src/utils/metadataDelta/utils.ts
- src/utils/tokens.ts
This is the feature branch for the Manage Tokens Refactor
> Feat: Manage Tokens Refactor

- package-lock.json
- package.json
- src/eventListeners/types.ts
- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/expenditureStateChanged.ts
- src/handlers/expenditures/helpers/createEditExpenditureAction.ts
- src/handlers/expenditures/helpers/decodeSetExpenditureState.ts
- src/handlers/expenditures/stagedPaymentReleased.ts
- src/handlers/motions/motionCreated/handlers/expenditures/releaseStagedPaymentViaArbitration.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicall.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/editLockedExpenditureMotion.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/fundExpenditureMotion.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/index.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/releaseStagedPaymentsMotion.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/types.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionCreated/motionCreated.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/types/events.ts
- src/types/methods.ts
- src/types/motions.ts
- src/utils/actionExists.ts
- src/utils/index.ts
- src/utils/parseFunction.ts
Reopening #243 as it got closed due to a bad rebase
> Feat: Releasing staged payments 

- src/graphql/fragments/expenditures.graphql
- src/graphql/fragments/motions.graphql
- src/graphql/generated.ts
- src/graphql/mutations/expenditures.graphql
- src/graphql/queries/expenditures.graphql
- src/handlers/expenditures/helpers/createEditExpenditureAction.ts
- src/handlers/expenditures/helpers/createEditStreamingPaymentAction.ts
- src/handlers/expenditures/helpers/handleEditOrCancelStreamingPaymentAction.ts
- src/handlers/expenditures/paymentTokenUpdated.ts
- src/handlers/expenditures/streamingPaymentEndTimeSet.ts
- src/handlers/expenditures/streamingPaymentStartTimeSet.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicall.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/editStreamingPaymentMotion.ts
- src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/index.ts
- src/handlers/motions/motionCreated/helpers.ts
- src/handlers/motions/motionFinalized/helpers.ts
- src/handlers/motions/motionFinalized/motionFinalized.ts
- src/interfaces.ts
- src/types/methods.ts
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2721)
> Feat: Edit streams using motions 

- src/graphql/generated.ts
Bridge typedefs welcome to the `generated.ts` file :hugs:
> build: realign graphql typedefs

- src/graphql/generated.ts
- src/graphql/queries/motions.graphql
- src/handlers/motions/motionFinalized/helpers.ts
- src/handlers/motions/motionFinalized/motionFinalized.ts
[See CDapp counterpart 2866](https://github.com/JoinColony/colonyCDapp/pull/2866)
> Feat: Update action when simple payment motion finalized to include networkFee and amountLessFee

- src/graphql/generated.ts
- src/handlers/multiSig/multiSigCreated/handlers/metadataDelta.ts
- src/handlers/multiSig/multiSigCreated/handlers/metadataDeltaHandlers/manageTokens.ts
[CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2910)
> Feat: Implement manage tokens via multi-sig

- src/handlers/motions/motionCreated/handlers/setUserRoles.ts
- src/handlers/multiSig/multiSigCreated/handlers/setUserRoles.ts
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2924)
> fix: create historic roles for motions too, fix check if roles are multi-sig condition when creating a multi-sig motion

- src/graphql/generated.ts
- src/graphql/mutations/motions.graphql
- src/graphql/queries/motions.graphql
- src/handlers/motions/motionVoteRevealed/helpers.ts
- src/handlers/motions/motionVoteRevealed/index.ts
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2917)
> feat: save motion voter rewards into the database

- src/handlers/colonies/transfer.ts
Prior to this fix, anything "acting" like a "valid" ERC-20 tokens could send any colony some amount of tokens.
Granted, the UI would have been filtering out the incoming transfer, if said token was not on the "approved" tokens list _(although you could still see it manipulating the filters)_
Now this is where the problem gets complicated. Let's say I create a contract that capable of transferring token amounts to other addresses _(a Colony in our example)_, but one which doesn't meet the [ERC-20 standard specification](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/) _(as low of a bar as that is)_. If such a token would make a transfer to an existing Colony, the transfer would be recorded, and the UI will fetch it as "valid" incoming funds, while simultaneous failing to …
> Prevent adding Incoming Funds Claims from Non Supported Tokens

- .env.example
- package-lock.json
- package.json
- src/graphql/fragments/users.graphql
- src/graphql/generated.ts
- src/graphql/queries/contributors.graphql
- src/handlers/actions/oneTxPayment.ts
- src/index.ts
- src/utils/graphql.ts
- src/utils/notifications.ts
Part of CDapp PR https://github.com/JoinColony/colonyCDapp/pull/3055
> Send notifications on simple payment action

- .env.example
- src/handlers/actions/oneTxPayment.ts
- src/utils/notifications.ts
Part of CDapp PR here: https://github.com/JoinColony/colonyCDapp/pull/3167
> Feat: Update custom attributes for notifications

- src/handlers/actions/colonyUpgrade.ts
- src/handlers/actions/createDomain.ts
- src/handlers/actions/editColony.ts
- src/handlers/actions/editDomain.ts
- src/handlers/actions/emitDomainReputation.ts
- src/handlers/actions/managePermissions.ts
- src/handlers/actions/mintTokens.ts
- src/handlers/actions/moveFunds.ts
- src/handlers/actions/oneTxPayment.ts
- src/handlers/actions/unlockToken.ts
- src/handlers/metadataDelta/handlers/addVerifiedMembers.ts
- src/handlers/metadataDelta/handlers/manageTokens.ts
- src/handlers/metadataDelta/handlers/removeVerifiedMembers.ts
- src/utils/permissions.ts
See description and testing steps in CDapp PR: https://github.com/JoinColony/colonyCDapp/pull/3205
> Send notifications on permissions actions

- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/graphql/queries/user.graphql
- src/handlers/actions/colonyUpgrade.ts
- src/handlers/actions/createDomain.ts
- src/handlers/actions/editColony.ts
- src/handlers/actions/editDomain.ts
- src/handlers/actions/emitDomainReputation.ts
- src/handlers/actions/managePermissions.ts
- src/handlers/actions/mintTokens.ts
- src/handlers/actions/moveFunds.ts
- src/handlers/actions/oneTxPayment.ts
- src/handlers/actions/unlockToken.ts
- src/handlers/expenditures/expenditureAdded.ts
- src/handlers/expenditures/expenditureCancelled.ts
- src/handlers/expenditures/expenditureFinalized.ts
- src/handlers/expenditures/expenditureLocked.ts
- src/handlers/expenditures/expenditureRecipientSet.ts
- src/handlers/metadataDelta/handlers/addVerifiedMembers.ts
- src/handlers/metadataDelta/handlers/manageTokens.ts
- src/handlers/metadataDelta/handlers/removeVerifiedMembers.ts
- src/utils/notifications.ts
- src/utils/permissions.ts
Part of CDapp PR: https://github.com/JoinColony/colonyCDapp/pull/3252
> Handle advanced payment notifications

- src/graphql/fragments/token.graphql
- src/graphql/generated.ts
- src/graphql/queries/funds.graphql
- src/handlers/colonies/colonyFundsClaimed.ts
- src/utils/notifications.ts
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3277)
> [Notifications] feat: send notification on claim funds event

- src/handlers/expenditures/stakeFractionSet.ts
- src/handlers/extensions/extensionDeprecated.ts
- src/handlers/extensions/extensionInitialised.ts
- src/handlers/extensions/extensionUninstalled.ts
- src/handlers/multiSig/domainSkillThresholdSet.ts
- src/handlers/multiSig/globalThresholdSet.ts
- src/utils/extensions/updateExtension.ts
- src/utils/extensions/writeExtension.ts
- src/utils/notifications.ts
[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/3290)
(Note: Also updated package-lock.json as it was breaking CDapp, but should probably be done on the feat/in-app-notifications branch)
> [Notifications] Feat: Extensions notifications

- src/graphql/generated.ts
- src/types/notifications.ts
- src/utils/extensions/writeExtension.ts
- src/utils/notifications.ts
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3358)
> [Notifications] feat: send notifications on new extension versions

- src/graphql/generated.ts
- src/handlers/expenditures/expenditurePayoutClaimed.ts
- src/types/notifications.ts
Add a new notification for expenditures when a payout is claimed.
CDapp PR here: https://github.com/JoinColony/colonyCDapp/pull/3400
> Feat: Add payout claimed notification

- src/graphql/generated.ts
- src/handlers/expenditures/expenditureMadeStaged.ts
- src/handlers/expenditures/expenditureMadeViaStake.ts
https://github.com/JoinColony/colonyCDapp/pull/3402
> Feat: Store related extension addresses on the expenditure object

- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/handlers/expenditures/expenditurePayoutClaimed.ts
[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/3619)
Seems like my formatting settings are different than whoever last ran codegen here as almost all the line changes are from the generated file...
> Fix: Split payment should not send multiple notifications

- src/graphql/generated.ts
- src/graphql/queries/action.graphql
- src/handlers/actions/makeArbitraryTransaction.ts
- src/utils/argsByTypeToString.ts
- src/utils/index.ts
This handler is related to https://github.com/JoinColony/colonyCDapp/issues/3535 and https://github.com/JoinColony/colonyCDapp/pull/3839. 
Copy the FOUR_BYTE_API_URL variable from .env.example to .env.
Note: updating action is a temporary solution unless @jakubcolony will do refactoring on block-ingestor.
> feat: implement arbitrary transactions handler

- apps/main-chain/src/eventListeners/proxyColonies.ts
- apps/main-chain/src/handlers/metadataDelta/handlers/disableProxyColony.ts
- apps/main-chain/src/handlers/metadataDelta/metadataDelta.ts
- apps/main-chain/src/handlers/proxyColonies/proxyColonyRequested.ts
- apps/main-chain/src/utils/metadataDelta/types.ts
- apps/main-chain/src/utils/metadataDelta/utils.ts
- apps/proxy-chain/src/eventListeners/proxyColonies.ts
- packages/blocks/src/events/eventManager.ts
- packages/blocks/src/events/types.ts
- packages/graphql/src/generated.ts
- packages/graphql/src/mutations/proxyColonies.graphql
- packages/graphql/src/queries/proxyColonies.graphql
This PR adds a new handler to the `metadataDelta` event for disabling a proxy colony.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/4006)
> Feat: Handle disable proxy colony metadataDelta event

- apps/main-chain/src/eventListeners/colony.ts
- apps/main-chain/src/eventListeners/proxyColonies.ts
- apps/main-chain/src/handlers/motions/motionCreated/handlers/proxyColonies/createProxyColony.ts
- apps/main-chain/src/handlers/motions/motionCreated/motionCreated.ts
- apps/main-chain/src/handlers/proxyColonies/proxyColonyRequested.ts
- apps/main-chain/src/types/motions.ts
- apps/main-chain/src/utils/actions/motions.ts
- apps/main-chain/src/utils/actions/writeAction.ts
- apps/proxy-chain/src/eventListeners/colony.ts
- apps/proxy-chain/src/eventListeners/proxyColonies.ts
- packages/blocks/src/events/eventManager.ts
- packages/blocks/src/events/types.ts
- packages/graphql/src/generated.ts
[CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/4036)
> [Proxy colonies] feat: createProxyColony motion

- src/utils/notifications.ts
CDapp changes here: https://github.com/JoinColony/colonyCDapp/pull/4121
> Chore: Turn off notifications in dev by default

- apps/main-chain/src/handlers/metadataDelta/handlers/disableProxyColony.ts
- apps/main-chain/src/handlers/metadataDelta/handlers/enableProxyColony.ts
- apps/main-chain/src/handlers/motions/motionCreated/handlers/metadataDelta.ts
- apps/main-chain/src/handlers/motions/motionCreated/handlers/proxyColonies/createProxyColony.ts
- apps/main-chain/src/handlers/multiSig/multiSigCreated/handlers/metadataDelta.ts
- apps/main-chain/src/handlers/multiSig/multiSigCreated/handlers/proxyColonies/createProxyColony.ts
- apps/main-chain/src/handlers/proxyColonies/proxyColonyRequested.ts
- packages/graphql/src/fragments/actions.graphql
- packages/graphql/src/generated.ts
CDapp PR here: https://github.com/JoinColony/colonyCDapp/pull/4145
> Move targetChainId up to the top level of colonyAction

- apps/proxy-chain/src/index.ts
- apps/proxy-chain/src/utils/addChainToDB.ts
- apps/proxy-chain/src/utils/cleanup.ts
- packages/graphql/src/generated.ts
- packages/graphql/src/mutations/proxyColonies.graphql
- packages/graphql/src/queries/proxyColonies.graphql
Upon startup, add the proxy chain to the DB and mark it as inactive when we shut down the ingestor.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/4161)
> [Proxy colonies M1] Feat: Dynamically add supported proxy chain

- src/handlers/actions/makeArbitraryTransaction.ts
Testing steps here: https://github.com/JoinColony/colonyCDapp/pull/4167
> feat: send notifications for arbitrary transactions

- src/utils/actions/writeAction.ts
CDapp PR here: https://github.com/JoinColony/colonyCDapp/pull/4217
> Fix: Dont show failed expenditures in actions list

- src/handlers/expenditures/stakeFractionSet.ts
- src/handlers/extensions/extensionDeprecated.ts
- src/handlers/extensions/extensionInitialised.ts
- src/handlers/extensions/extensionUninstalled.ts
- src/handlers/multiSig/globalThresholdSet.ts
- src/utils/extensions/writeExtension.ts
- src/utils/transactions.ts
[See CDapp counterpart for details](https://github.com/JoinColony/colonyCDapp/pull/4220)
> Fix: Replace receipt.from with transaction signer address
