.eslintrc.js, src/amplifyClient.ts, src/eventListener.ts, src/eventProcessor.ts, src/index.ts, src/trackExtensions.ts, src/types.ts, src/utils.ts
This required some changes to how events are listened for in the block-ingestor and my solution feels quite hacky so @rdig feel free to suggest alternatives.
When `ExtensionInstalled` event is picked up, block-ingestor will start listening for `ExtensionInitialised` event specific to that extension instance. It will then update the extension in the database to reflect its initialised status.
For extensions that had been installed before the block-ingestor started, there's a new `trackExtensions` function for each supported extension (currently just the VotingReputation) will iterate over and sum the number of installed and uninstalled events. If the number of installations is higher than uninstallation, it will add an `ExtensionInitialised` event listener for that particular extension in …
=> Handle `ExtensionInitialised` event

src/amplifyClient.ts, src/constants.ts, src/eventListener.ts, src/eventProcessor.ts, src/trackColonies.ts, src/types.ts
This PR adds two concepts of tracking colony version:
1. Tracking the highest colony version available in the network
2. Tracking the current versions of individual colonies 
To achieve 1), we listen to the `ColonyVersionAdded` event and utilise the existing `CurrentVersion` model already used for tracking highest available extension versions:
```gql
type CurrentVersion @model {
id: ID!
key: String! @index(name: "byKey", queryField: "getCurrentVersionByKey")
version: Int!
}
```
For extensions, `key` represents the extension hash, in case of colonies, since there's only one type to track, `key` is set to `colony` string.
Additionally, we write the current highest version to the db on ingestor startup.
For 2), there is a new `version` field on Colony model that gets updated on …
=> Track colony versions in the database

src/constants.ts, src/eventListener.ts, src/eventProcessor.ts, src/trackColonies.ts, src/trackExtensions.ts, src/utils/events.ts, src/utils/extensions.ts, src/utils/index.ts, src/utils/logger.ts, src/utils/numbers.ts, src/utils/stats.ts
This PR adds tracking of extension events that happened before block-ingestor has started, ensuring the db stays up to date.
The tracking logic can be split in two parts: tracking current extension version and tracking extension installation events.
Latest block number refers to the latest block processed by block-ingestor that is stored in `run/stats.json`.
For every supported extension, we fetch the `ExtensionAddedToNetwork` events, starting from the latest block processed by the block-ingestor. It takes the most recent event (since we only care about the most recent version anyway) and if exists, writes the version to the database.
For every supported extension, we fetch **all** `ExtensionInstalled` and `ExtensionUninstalled` events and then create a mapping between colony address and …
=> Write extension data to the db on ingestor start

src/eventProcessor.ts, src/handlers/actions/index.ts, src/handlers/actions/moveFunds.ts, src/types.ts, src/utils/actions/listener.ts
This is a parallel PR to https://github.com/JoinColony/colonyCDapp/pull/291
Please refer to that PR for testing instructions
=> Add support for MoveFunds action

src/utils/events.ts
This small PR facilitates the renaming of ContractEvent `meta` field to `chainMetadata`.
=> Extract colony metadata from colony model

src/trackColonies.ts, src/trackColonyActions.ts, src/types.ts, src/utils/events.ts
This PR adds tracking of past actions that might have happened when block-ingestor was down.
Similarly to extensions tracking, it currently goes through all events since block number 1 and I opened an issue to change it in the future: #39 
Testing involves triggering all the supported actions while block-ingestor is disabled (so you need to start the CDapp on `master` without it running), then running the ingestor separately and verifying that the actions have been picked up and written to the database.
=> Track past actions 

src/handlers/actions/createDomain.ts, src/handlers/actions/emitDomainReputation.ts, src/handlers/actions/moveFunds.ts, src/handlers/actions/payment.ts, src/handlers/actions/unlockToken.ts, src/trackColonies.ts, src/trackColonyActions.ts, src/trackExtensions.ts, src/types.ts, src/utils/colonyClient.ts, src/utils/events.ts, src/utils/index.ts, src/utils/tokens.ts
This PR adds caching of colony clients. It was originally suggested by Raul in one of my PRs and it made sense to do it now as I found myself calling `getColonyClient` in different methods for the same colony
Resolves #25
=> Cache colony clients

src/eventListener.ts, src/eventProcessor.ts, src/handlers/motions/index.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionRewardClaimed.ts, src/types/index.ts, src/types/motions.ts
This PR adds block ingestor support for motion reward claimed events. Test with this branch: https://github.com/JoinColony/colonyCDapp/pull/324/ 
(note that in the cdapp branch, we actually point to https://github.com/JoinColony/block-ingestor/pull/42, which is based off this branch. This in intentional)
=> Add motion reward claimed support

src/amplifyClient.ts, src/handlers/motions/helpers.ts, src/handlers/motions/motionCreated/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionRewardClaimed.ts, src/handlers/motions/motionStaked/motionStaked.ts, src/types/motions.ts
This pr updates the relevant motion handlers to fetch the motion from the db using the unique database id, as opposed to using the native id and sorting by created date.
=> Make unique database motion id

src/amplifyClient.ts, src/eventListener.ts, src/eventProcessor.ts, src/handlers/motions/helpers.ts, src/handlers/motions/index.ts, src/handlers/motions/motionCreated/helpers.ts, src/handlers/motions/motionCreated/index.ts, src/handlers/motions/motionCreated/motionCreated.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/index.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionRewardClaimed.ts, src/handlers/motions/motionStaked/helpers.ts, src/handlers/motions/motionStaked/motionStaked.ts, src/types/index.ts, src/types/motions.ts, src/utils/clients.ts, src/utils/index.ts, src/utils/motions.ts
This PR handles the database mutation for the MotionStaked event.
It introduces a number of helpers in order to calculate the latest staking data, for consumption by the staking widget in the front end, and then mutates the motionData field of the corresponding ColonyAction.
Test with [port/270-update-ui-after-staking](https://github.com/JoinColony/colonyCDapp/pull/338)
=> Add db mutations for motion staking

src/handlers/motions/motionStaked/helpers.ts
This PR ensures that the staking percentage is never calculated as zero, since it's impossible for a user to stake 0% of a motion. 
This might happen due to rounding when staking the minimum stake. In this case, we round up to 1.
=> Fix staking percentage calculation when staking min

src/amplifyClient.ts, src/constants.ts, src/eventListener.ts, src/eventProcessor.ts, src/handlers/index.ts, src/handlers/network/index.ts, src/handlers/network/networkFeeInverseSet.ts, src/index.ts, src/trackNetworkInverseFee.ts, src/types.ts
This PR adds support for the `NetworkFeeInverseSet` event emitted every time the inverse fee is updated by Network.
Let me know if the logic or flow sounds good to you guys. This is my first time implementing something in the `block-ingestor` and I tried to take existing code as an example for this.
Corresponds with https://github.com/JoinColony/colonyCDapp/pull/325
=> Add NetworkFeeInverseSet event handler

src/amplifyClient.ts, src/handlers/motions/helpers.ts, src/handlers/motions/motionCreated/helpers.ts, src/handlers/motions/motionStaked/motionStaked.ts, src/utils/actions/writeAction.ts
This PR adds a flag to actions and motions indicating whether they should appear in the actions list. Test with https://github.com/JoinColony/colonyCDapp/pull/410
It's:
- true for actions that were not initiated by a voting rep extn
- true for motions if total stake >= 10 %
- else false
=> Add actions list support

src/amplifyClient.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/types/motions.ts
CDapp counterpart: https://github.com/JoinColony/colonyCDapp/pull/471
`Domain` with their `DomainMetadata` created via motion:
Pending `DomainMetadata` of an edit to the domain previously created:
The previous pending `DomainMetadata` now linked to the edited domain:
=> Add support for pending domain metadata on finalized motions

src/handlers/motions/motionCreated/handlers/payment.ts
Fix payment motion handler taking `motionDomainId` as `fromDomainId`.
Related CDapp PR: https://github.com/JoinColony/colonyCDapp/pull/486
=> Fix payment motion's `fromDomainId`

src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionStaked/helpers.ts
[colonyCDapp#520](https://github.com/JoinColony/colonyCDapp/pull/520) makes initiatorAddress required with the change when refactoring motion messages to be a model
Currently SystemMessages do not have an initiatorAddress set, this PR will set initiatorAddress to AddressZero
Contributes to colonyCDapp#423
=> Set initiatorAddress to AddressZero

src/handlers/actions/mintTokens.ts
> The action list item for the mint tokens action is not displaying the team in the meta info, which should be "Root”:
Found while testing on QA.
To test this, just replace the commit hash in `master`, create a mint tokens action, and check that the meta info of the action list item includes the `Root` domain:
=> Add missing `fromDomainId` to `mintTokens` handler

.gitignore, package-lock.json, package.json, src/blockListener.ts, src/handlers/colonies/colonyAdded.ts, src/index.ts, src/provider.ts, src/stats.ts, src/trackColonies.ts, src/trackColonyActions.ts, src/trackExtensions.ts, src/utils/stats.ts, stats/446501053769c06c565094b26d26e8ef
This optimisation allows block-ingestor to pick up right where it left off before restart, rather than having to go from block 1. It uses `node-persist` library for easier persistent storage (which still uses JSON files, but has a nicer interface)
I imagine this approach will only get tested property in the QA environment, but for now:
1. Run the ingestor on this branch separately
2. Run the `temp-create-data` script in CDapp
3. Restart the ingestor. On `master`, you'd see a bunch of failed mutations related to extensions and actions. On this branch, there shouldn't be more than 1-2 failed mutations (I suspect these are due to ganache/block-ingestor replaying some of the transactions)
TODO:
=> Track extensions, colonies and actions from the latest processed block

src/amplifyClient.ts, src/handlers/motions/motionCreated/handlers/editColony.ts, src/handlers/motions/motionCreated/handlers/index.ts, src/handlers/motions/motionCreated/motionCreated.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/types/index.ts, src/types/motions.ts, src/utils/arrays.ts, src/utils/colonyClient.ts, src/utils/domains.ts, src/utils/tokens.ts
This PR adds support for the manage tokens motion. Test with https://github.com/JoinColony/colonyCDapp/pull/553.
It works the same as Domains.
In the editColonyMotion saga, we create a "pending" colonyMetadata object that represents the intended state change.
When a successful motion is finalized, we update the actual colony metadata with the changes, and update the colony tokens if needed. 
Note that I've implented this so that, in theory, we won't be overwriting metadata state changes that occurred after the motion was created (as currently happens with the domain metadata). I have only been able to test that this is true for adding / removing tokens as other colonyEditMotion functionality is yet to be wired (this should also be tested then).
=> Wire Manage Tokens / Edit Colony motion

src/amplifyClient.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/types/motions.ts
This pr ensures that only the domain metadata that was changed by a motion gets updated in the database. 
Previously, the behaviour was updating the entire domain metadata state with the entire pendingMetadata state, which meant that any changes occuring to the domain metadata after the motion was created, even ones that were not explicitly changed by the motion, would be overwritten.
For example:
Motion 1 created: changes color from to blue to green
Motion 2 created: changes description. Doesn't change color at all.
Motion 1 finalizes, and color changes to green.
Motion 2 finalizes, and changes color back to blue, because that was the color when Motion 2 was created. Expected behaviour would be to leave color alone, because the motion didn't change the color of the domain, only the …
=> Refactor updating domain metadata on motion finalized

src/amplifyClient.ts, src/handlers/motions/helpers.ts, src/handlers/motions/motionCreated/helpers.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionRewardClaimed.ts, src/handlers/motions/motionStaked/helpers.ts, src/handlers/motions/motionStaked/motionStaked.ts, src/handlers/motions/motionVoteRevealed/index.ts, src/handlers/motions/motionVoteSubmitted/index.ts, src/types/actions.ts, src/types/index.ts, src/types/motions.ts
Moved `motionData` inside `ColonyAction` to their own model (`ColonyMotion`). Let me know if there's any part inside the ingestor that I forgot to update.
Also made some changes to how we create motion messages to actually link them to the motions.
`colonyCDapp`'s counterpart PR: https://github.com/JoinColony/colonyCDapp/pull/527
Resolves colonyCDapp#356
=> Separate MotionData from ColonyAction into its own model

src/amplifyClient.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionRewardClaimed/helpers.ts, src/handlers/motions/motionRewardClaimed/index.ts, src/handlers/motions/motionRewardClaimed/motionRewardClaimed.ts, src/types/index.ts
This PR adds block ingestor support for the Stakes Tab in the Token Activation Popover.
Test with: https://github.com/JoinColony/colonyCDapp/pull/591
=> Add unclaimed stakes support

src/handlers/motions/motionStaked/helpers.ts
For a user stake, there are a few places in the staking UI where a 0% user stake is displayed and this can conflict with the motion stake percentage that always shows a minimum of 1%.
Since its not possible for a user to stake 0% and it visually makes more sense to show 1% since we don't show fractional percentages, this fix makes it so the minimum percent for a user stake is always 1%.
Contributes to colonyCDapp#648
=> Round user stake percentage to 1 if percentage is zero due to rounding

src/handlers/actions/payment.ts
Currently, if you make a payment from one colony to another, the claim event will not be shown in the colony ui, meaning the user cannot claim the funds in the recipient colony. 
This PR checks when making a payment if the recipient is a colony, and if so, will add the claim to the db.
Use branch: https://github.com/JoinColony/colonyCDapp/pull/718
In Colony A, make a payment to Colony B using Colony A native token.
In Colony B, you can now see the incoming funds claim.
If you add the token to Colony B's balances, you will see it appear after claiming.
=> Ensure claim shows when transferring between colonies

src/amplifyClient.ts, src/graphql/generated.ts, src/graphql/mutations/user.graphql, src/graphql/queries/user.graphql, src/handlers/motions/helpers.ts, src/handlers/motions/motionRewardClaimed/helpers.ts, src/handlers/motions/motionRewardClaimed/motionRewardClaimed.ts, src/handlers/motions/motionStaked/helpers.ts, src/handlers/motions/motionStaked/motionStaked.ts
Note: ~200 lines are from `generated.ts`.
This PR adds support for displaying the amount of tokens a user has staked in a colony to the block ingestor. Test with: https://github.com/JoinColony/colonyCDapp/pull/704
=> Add support for displaying staked tokens in Token Activation Popover

src/eventListeners/colony.ts, src/eventProcessor.ts, src/handlers/expenditures/expenditureCancelled.ts, src/handlers/expenditures/index.ts
This PR adds a handler for the `ExpenditureCancelled` event. 
Once you've tested this PR I recommend testing #105 since many testing steps are common.
```js
c.makeExpenditure(1, UINT256_MAX, 1)
```
2. You can use the following query to verify the expenditure has been stored in the DB (and its status is `DRAFT`):
```gql
query ListExpenditures {
listExpenditures {
items {
id
status
}
}
}
```
3. Cancel the expenditure with the following command:
```js
// If it's the first expenditure you created, the (native) ID will be 1, …
```
=> Handle expenditure cancellation

src/eventListeners/colony.ts, src/eventProcessor.ts, src/handlers/expenditures/expenditureFinalized.ts, src/handlers/expenditures/index.ts
This PR adds a handler for the `ExpenditureFinalized` event. 
```js
c.makeExpenditure(1, UINT256_MAX, 1)
```
2. You can use the following query to verify the expenditure has been stored in the DB (and its status is `DRAFT`):
```gql
query ListExpenditures {
listExpenditures {
items {
id
status
}
}
}
```
3. Finalize the expenditure with the following command:
```js
// If it's the first expenditure you created, the (native) ID will be 1, then it goes up incrementally:
c.finalizeExpenditure(1)
```
4. Using the query above, …
=> Handle expenditure finalization

src/eventListeners/colony.ts, src/eventProcessor.ts, src/handlers/expenditures/expenditureTransferred.ts, src/handlers/expenditures/index.ts
This PR adds a handler for the `ExpenditureTransferred` event. 
```js
c.makeExpenditure(1, UINT256_MAX, 1)
```
2. You can use the following query to verify the expenditure has been stored in the DB with your wallet address as the `ownerAddress`.
```gql
query ListExpenditures {
listExpenditures {
items {
id
ownerAddress
}
}
}
```
3. Transfer the expenditure ownership with the following command:
```js
// If it's the first expenditure you created, the (native) ID will be 1, then it goes up incrementally: …
```
=> Handle expenditure transfer

src/eventListeners/colony.ts, src/eventProcessor.ts, src/graphql/generated.ts, src/graphql/queries/expenditures.graphql, src/handlers/expenditures/expenditureClaimDelaySet.ts, src/handlers/expenditures/expenditureGlobalClaimDelaySet.ts, src/handlers/expenditures/index.ts, src/types/events.ts
This PR adds handlers for `ExpenditureGlobalClaimDelaySet` and `ExpenditureClaimDelaySet` events.
```js
```
1. Use the following query to verify there's no global claim delay set:
```gql
query GetColony {
getColony(id: "<your colony address>") {
expendituresGlobalClaimDelay
}
}
```
2. In truffle console, set the global claim delay:
```js
c.setDefaultGlobalClaimDelay(100) // 100 seconds
```
3. Verify the claim delay has been correctly stored on the colony object.
1. Run the following commands in truffle:
```js …
```
=> Handle setting expenditure claim delay

src/eventListeners/colony.ts, src/eventProcessor.ts, src/graphql/generated.ts, src/graphql/queries/expenditures.graphql, src/handlers/expenditures/expenditurePayoutModifierSet.ts, src/handlers/expenditures/index.ts, src/types/events.ts
This PR adds a handler for ExpenditurePayoutModifierSet event.
```js
c.makeExpenditure(1, UINT256_MAX, 1)
// Set payout modifier of 100 for slot 1
c.setExpenditurePayoutModifiers(1, [1], [100]) // arguments: expenditure id, array of slot numbers, array of modifiers
```
2. Use the following query to verify the modifier has been stored:
```gql
query ListExpenditures {
listExpenditures {
items {
slots { 
id
payoutModifier
} 
}
}
}
```
=> Handle setting expenditure payout modifier

src/graphql/fragments/colony.graphql, src/graphql/generated.ts, src/graphql/queries/colony.graphql, src/handlers/actions/emitDomainReputation.ts
This PR fixes a bug that causes the block ingestor to crash. 
In the arbitrary reputation update handler, we were using event logs to find a domain instead of the db. Lots of logs lead to an rpc timeout, leading to the block ingestor crashing.
=> Fix arbitrary reputation update handler

src/constants.ts, src/graphql/generated.ts, src/graphql/mutations/extension.graphql, src/graphql/queries/extensions.graphql, src/handlers/extensions/extensionInstalled.ts, src/utils/extensions/index.ts, src/utils/extensions/installationCount.ts
This PR provides support for displaying the global number of extension installations for an extension.
https://github.com/JoinColony/colonyCDapp/pull/1170
=> Support for active installs in db

src/handlers/motions/motionCreated/helpers.ts
This PR fixes an issue where the motion's `createdAt` date is set to the system current time rather than the block timestamp.
=> Ensure block timestamp is saved as motion createdAt date

src/blockListener.ts
If error is not thrown, block ingestor hangs and needs to be manually restarted
=> Throw error when failed to get a block

src/handlers/colonies/colonyAdded.ts
I noticed the create data script failing with the max retries set to 3, this gives it a better chance to catch up.
=> Increase max retries for colony metadata query

src/handlers/actions/createDomain.ts, src/handlers/actions/moveFunds.ts, src/handlers/actions/oneTxPayment.ts, src/handlers/actions/unlockToken.ts, src/handlers/expenditures/paymentTokenUpdated.ts, src/handlers/expenditures/streamingPaymentCreated.ts, src/handlers/extensions/extensionInstalled.ts, src/handlers/motions/motionCreated/handlers/mintTokens.ts, src/handlers/motions/motionCreated/handlers/moveFunds.ts, src/handlers/motions/motionCreated/handlers/unlockToken.ts, src/handlers/motions/motionCreated/motionCreated.ts, src/handlers/motions/motionFinalized/helpers.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionStaked/motionStaked.ts, src/handlers/motions/motionVoteRevealed/index.ts, src/handlers/motions/motionVoteSubmitted/index.ts, src/handlers/tokens/setTokenAuthority.ts, src/utils/tokens.ts
This PR refactors **all** the contract read calls we make in the block ingestor _(ie: every time we call a method on an instantiated `colonyJS` client)_ by making sure the data we read is historically correct to the time the event actually happened.
This is accomplished by getting the block number of the specific event we handle, and passing it in the [CallOverrides](https://docs.ethers.org/v5/api/contract/contract/#Contract-functionsCall) options object
This way we ensure that every time we read a specific piece of data from the contracts, be it now, or in the past, it will have always the exact same, correct value.
This change in this PR helps avoid various race conditions that will start happening once the block ingestor is under heavier load, as well as giving the block ingestor the …
=> Read contract data at the time the event happened

src/eventListeners/colony.ts, src/eventProcessor.ts, src/graphql/generated.ts, src/graphql/mutations/verifiedMembers.graphql, src/handlers/index.ts, src/handlers/metadataDelta/handlers/addVerifiedMembers.ts, src/handlers/metadataDelta/index.ts, src/handlers/metadataDelta/metadataDelta.ts, src/handlers/metadataDelta/types.ts, src/handlers/metadataDelta/utils.ts, src/types/events.ts
Added a new handler for the `ColonyMetadataDelta` event. 
The handler tries to parse the event via type guards, it currently only has support for adding verified members.
Using this approach it should be easy to implement removing of verified members.
Easiest way is to:
1. Stop the block ingestor while running `npm run dev`, and run this branch instead.
2. spin up the CDapp on [this branch](https://github.com/JoinColony/colonyCDapp/pull/1773).
3. Choose a member that hasn't been verified yet and copy their address 
4. go to the colony dashboard home, where the temporary component for verifying members lives, paste the address and click `Verify`
5. Check logs to see that block-ingestor processed the transaction
6. Use GraphQL query `getVerifiedMembersByColony` to check which users are …
=> [Verified members] feat: block ingestor can now catch MetadataDelta events and parse operations, implement add verified members

src/graphql/generated.ts, src/handlers/motions/motionCreated/handlers/metadataDelta.ts
Added support for removing verified members to the `ColonyMetadataDelta` event handler.
Easiest way is to:
1. Stop the block ingestor while running `npm run dev`, and run this branch instead.
2. spin up the CDapp on [this branch](https://github.com/JoinColony/colonyCDapp/pull/1891).
3. Enable the permissions extension
4. Choose a verified member and copy their address 
5. go to the colony dashboard home, where the temporary component for unverifying members lives, paste the address and click `Unverify via motion`
6. Fully support the motion
7. run `curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[300],"id":1}' localhost:8545` to forward the time by 5 minutes
8. Finalize the motion, claim rewards, ...
9. Use GraphQL query `getVerifiedMembersByColony` to check …
=> [Verified members] Implement remove verified members motion

src/eventListeners/colony.ts, src/eventListeners/extension/index.ts, src/types/events.ts
New colony network versions and extension versions were not being picked up by block ingestor. This was due to the event listeners not be properly initialised.
This PR ensures the event listeners are initialised correctly.
Resolves #169
=> Fix: New Colony network version and extensions are not being picked up

src/blockListener.ts, src/blockProcessor.ts, src/constants.ts, src/graphql/generated.ts, src/handlers/actions/createDomain.ts, src/handlers/actions/oneTxPayment.ts, src/provider.ts, src/types/events.ts, src/utils/events.ts, src/utils/fundsClaims.ts
While exploring the possibility of deploying on Arbitrum, a make-or-break issue was found with the block ingestor:
This is primarily because blocks on Arbitrum are 25x more frequent than they are on Gnosis (five-per-second and one-per-five-seconds, respectively). The block ingestor was able to process 100 blocks per 10-12 seconds; this is enough to keep pace and eventually sync, but if a resync was ever required (which it will be) it would have been essentially impossible.
From initial testing, this PR appears to increase the syncing performance of the block ingestor by a factor of 40 or 50, at least in the regime where most blocks do not contain transactions of interest and we have few if any colonies tracked. This makes syncing much more comfortable. There are some optimisations that …
=> Minimise number of RPC calls made while syncing

src/handlers/expenditures/expenditurePayoutClaimed.ts, src/utils/index.ts, src/utils/transactionHasEvent.ts
Incoming funds were incorrectly being duplicated. This was due to both the 'transfer' and 'expenditurePayoutClaimed' events being emitted when a payment is made from one colony to another via the OneTxPayment extension.
This PR adds a check to the 'expenditurePayoutClaimed' event to check if the event was emitted by the OneTxPayment extension and to skip creating a new claim if so (as the 'transfer' event will already do this).
1. Send funds to a colony. (Copy the colony wallet address, switch to another colony, create a simple payment action with the colony address as the recipient)
2. Navigate to the incoming funds page.
3. The incoming funds should correctly show no duplicates.
You can also verify no duplicates are being created in the database:
```
query MyQuery {
listColonies {
items …
```
=> Fix: Duplicate incoming funds

src/graphql/fragments/motions.graphql, src/graphql/generated.ts, src/handlers/motions/motionCreated/helpers.ts, src/utils/actions/writeAction.ts
CDapp PR: https://github.com/JoinColony/colonyCDapp/pull/2035
This PR updates the parts of the block ingestor that were using and inserting the root hash on the motion model, now it should be on the action model so that it's available on motions and actions at the same time.
=> Move `rootHash` to action model

src/eventListeners/extension/votingReputation.ts, src/eventProcessor.ts, src/graphql/fragments/motions.graphql, src/graphql/generated.ts, src/handlers/motions/index.ts, src/handlers/motions/motionEventSet/index.ts, src/handlers/motions/motionFinalized/motionFinalized.ts, src/handlers/motions/motionStaked/motionStaked.ts, src/handlers/motions/motionVoteRevealed/index.ts, src/types/events.ts
This PR adds a bunch of timestamps to display the time when a motion phase was started/ended. These timestamps are displayed on the motion step pills, all the variations can be observed here: https://www.notion.so/colony/Actions-775cb0e78eb44783a6f28702b7a9dc33#72f018e16a234ef5944613c02ca1846a
I've added a `MotionEventSet` handler for timestamps that weren't easy, or outright not possible to get with the other events.
CDapp PR counterpart: https://github.com/JoinColony/colonyCDapp/pull/1625
=> Add motion timestamps to motion state history

src/handlers/colonies/colonyAdded.ts, src/utils/graphql.ts
> ## Disclamer
>
> This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
>
> We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
>
> This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
This is actually just a fix of the `tryFetchGraphqlQuery` util _(work done by @jakubcolony)_ which is used to "wait" until a colony's metadata exist, then proceed with the …
=> Fix Colony Creation (on networks with faster block time)

.env.example, src/blockListener.ts, src/blockProcessor.ts, src/constants.ts, src/types/events.ts, src/utils/events.ts
> ## Disclamer
>
> This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
>
> We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
>
> This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
Most, well... rather all work in this PR has been actually done by @area so all kudos go to him.
This change comes as a response to our Arbitrum deployment and it's way faster …
=> Optimize Block Processing

src/graphql/generated.ts, src/graphql/mutations/funds.graphql, src/graphql/queries/funds.graphql, src/handlers/colonies/colonyFundsClaimed.ts, src/utils/fundsClaims.ts
Update the colonyFundsClaimed handler to keep incoming funds in the database once they are claimed.
To test, run your cdapp with this commit as the commit hash for your block-ingestor image.
Create an incoming fund in a colony, and claim it.
It should still exist in the db, but with `isClaimed` set to true.
=> Keep incoming funds in db after claiming

src/graphql/fragments/colony.graphql, src/graphql/generated.ts, src/handlers/colonies/helpers/createUniqueColony.ts, src/handlers/metadataDelta/handlers/addVerifiedMembers.ts, src/handlers/motions/motionFinalized/helpers.ts, src/utils/contributors.ts, src/utils/permissions.ts
This PR will now allow any wallet addresses to be a Colony contributor which should satisfy this AC: "You should be able to verify addresses, even if they are not members"
It also removes all references to a Colony whitelist and is done as part of [colonyCDapp#2450](https://github.com/JoinColony/colonyCDapp/pull/2450) to address issue [colonyCDapp#2314](https://github.com/JoinColony/colonyCDapp/issues/2314).
New Contributors added via the Manage Verified Members flow should not be able to view the Colony right away. They should still have to go through the Colony invite flow.
Because this is a dependency for [colonyCDapp#2450](https://github.com/JoinColony/colonyCDapp/pull/2450), I will need to liaise with a fellow dev (most likely @jakubcolony) to make sure that both PRs are merged at …
=> fix: Allow any wallet address to be a verified member

src/eventListeners/extension/index.ts
It looks like by mistake, we never awaited promises inside `setupListenersForExtensions` which meant the event processing would potentially start before the listeners were in place.
I noticed this when testing https://github.com/JoinColony/colonyCDapp/pull/2490.
- Create a motion
- Disable block-ingestor (it will need to be run outside Docker at that point)
- Stake/oppose the motion
- Enable block-ingestor
In `master`, the stake event would not get picked up by ingestor and get lost without updating the motion. This fix should rectify that issue.
=> Fix: ingestor possibly skipping some events

src/eventProcessor.ts, src/graphql/generated.ts, src/handlers/expenditures/index.ts, src/handlers/expenditures/streamingPaymentClaimWaived.ts, src/types/events.ts
This is a dependency of [colonyCDapp#2515: Feat: Handle the cancelAndWaive method call for Streaming Payments](https://github.com/JoinColony/colonyCDapp/pull/2515)
=> Feat: handle the StreamingPayments contract's ClaimWaived event emission

src/graphql/generated.ts, src/handlers/motions/motionCreated/handlers/index.ts, src/handlers/motions/motionCreated/handlers/streamingPayments.ts/cancelStreamingPaymentsMotion.ts, src/handlers/motions/motionCreated/handlers/streamingPayments.ts/index.ts, src/handlers/motions/motionCreated/helpers.ts, src/handlers/motions/motionCreated/motionCreated.ts, src/types/motions.ts
These changes are required to test [colonyCDapp#2519: Feat: enable Payment Stream cancellation via a Motion](https://github.com/JoinColony/colonyCDapp/pull/2519)
=> Feat: enable handler for the cancel streaming payment motion

src/handlers/multiSig/multiSigCreated/handlers/index.ts, src/handlers/multiSig/multiSigCreated/handlers/metadataDelta.ts, src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
Create and finalize multi-sig add and remove verified members motions.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2650)
=> Fix: Manage verified users for multi-sig

src/graphql/fragments/colony.graphql, src/graphql/generated.ts, src/handlers/multiSig/multiSigCreated/handlers/editColony.ts, src/handlers/multiSig/multiSigCreated/handlers/index.ts, src/handlers/multiSig/multiSigCreated/multiSigCreated.ts, src/utils/colonyMetadata.ts
Create and finalize a multi-sig edit colony details and manage colony objective motions.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2654)
=> Feat: Edit colony description and objective for multi-sig

src/handlers/actions/managePermissions.ts
This PR fixes an issue with how we build a historic role's ID.
Historic roles IDs will now conditionally have the "_multisig" chunk when a multi-sig role is being processed.
Please test this as part of: [colonyCDapp#2773: Auto-populate the Role and Permissions fields in the Manage Permissions form ](https://github.com/JoinColony/colonyCDapp/pull/2773)
=> Fix: conditionally add multisig chunk to historic role id

src/graphql/generated.ts, src/handlers/motions/motionCreated/handlers/addDomain.ts, src/handlers/motions/motionCreated/handlers/editColony.ts, src/handlers/motions/motionCreated/handlers/editDomain.ts, src/handlers/motions/motionCreated/handlers/expenditures/cancelExpenditureViaArbitration.ts, src/handlers/motions/motionCreated/handlers/expenditures/cancelStakedExpenditures.ts, src/handlers/motions/motionCreated/handlers/expenditures/finalizeExpenditureViaArbitration.ts, src/handlers/motions/motionCreated/handlers/makeArbitraryTransactions.ts, src/handlers/motions/motionCreated/handlers/metadataDelta.ts, src/handlers/motions/motionCreated/handlers/metadataDeltaHandlers/manageTokens.ts, src/handlers/motions/motionCreated/handlers/mintTokens.ts, src/handlers/motions/motionCreated/handlers/moveFunds.ts, src/handlers/motions/motionCreated/handlers/multicall/multicall.ts, src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/editLockedExpenditureMotion.ts, src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/fundExpenditureMotion.ts, src/handlers/motions/motionCreated/handlers/multicall/multicallHandlers/types.ts, src/handlers/motions/motionCreated/handlers/networkUpgrade.ts, src/handlers/motions/motionCreated/handlers/payment.ts, src/handlers/motions/motionCreated/handlers/reputation.ts, src/handlers/motions/motionCreated/handlers/setUserRoles.ts, src/handlers/motions/motionCreated/handlers/simpleDecision.ts, src/handlers/motions/motionCreated/handlers/unlockToken.ts, src/handlers/motions/motionCreated/helpers.ts, src/handlers/motions/motionCreated/motionCreated.ts
This PR removes all gas estimation from the block ingestor in favor of calling different contracts as defined in its [CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2817)
=> feat: remove gas estimation for motions

src/handlers/metadataDelta/handlers/manageTokens.ts
This just simply adds a `fromDomainId` entry which ends up exposing the `fromDomain.metadata` information for the action.
Please test this as part of [colonyCDapp#2944 Fix: Reveal domain for manage tokens action
](https://github.com/JoinColony/colonyCDapp/pull/2944)
=> Fix: Reveal domain for manage tokens action

src/handlers/actions/moveFunds.ts, src/handlers/expenditures/expenditurePayoutClaimed.ts, src/utils/expenditures.ts
This is a temporary change that mitigates the issue where the expenditure balance drops below 0, affecting the total colony balance.
The current theory is that it's due to a race condition in DynamoDB, meaning the expenditure is not in the DB by the time we process the funds transferred into the expenditure's pot. On the other hand the expenditure is returned when payout is claimed, leading to the negative balance.
=> Temp: Prevent expenditure balance from going below 0, add logs

src/utils/notifications.ts
Quite basic, just don't send mention notifications if the recipient address is the same as the creator address.
This avoids notifications which are like: "You mentioned yourself in: Action 1" which just clog up your notification feed.
CDapp PR https://github.com/JoinColony/colonyCDapp/pull/3394 has testing steps :)
=> Dont send mention notifications to the same address as the creator

src/handlers/multiSig/approvalChanged/approvalChanged.ts
When a multisig is fully approved, we should ensure that only one notification is fired about this approval. Previously one notification was being sent for each role the user voted with, which in the case of a simple payment for example is three, so you would end up with three notifications all at the same time saying that the multisig motion was approved.
CDapp PR here https://github.com/JoinColony/colonyCDapp/pull/3396 has the testing steps.
=> Fix: Only fire one notification on multisig approval

src/handlers/expenditures/helpers/createEditExpenditureAction.ts
A subtle change without which setting new token for a payout while also editing an existing one did not work.
Consider the following scenario:
The UI wants to change a payout token from Token A to Token B. Since payouts can have multiple tokens, this process requires two steps: setting the new amount for Token B and setting Token A's amount to 0.
block-ingestor picks up the first `ExpenditurePayoutSet` for Token B and adds the updated payout to existing slot. However, when processing the second event, instead of applying the update to the recently modified slot, it incorrectly applies it to the original, unmodified slot. This results in the loss of Token B's payout information.
=> Fix: Edit expenditure updating payouts when token changes

src/handlers/motions/motionCreated/handlers/setUserRoles.ts, src/handlers/multiSig/multiSigCreated/handlers/setUserRoles.ts, src/utils/permissions.ts
Instead of getting the "delta" state and applying just the difference in roles in our database, we should just use whatever the FE passed to the contracts and apply it.
[CDApp PR](https://github.com/JoinColony/colonyCDapp/pull/3490)
=> fix: always use roles passed to contract for motions

apps/main-chain/src/handlers/proxyColonies/proxyColonyRequested.ts, apps/main-chain/src/multiChainBridgeClient.ts, apps/proxy-chain/src/eventListeners/colony.ts, apps/proxy-chain/src/handlers/proxyColonies/proxyColonyDeployed.ts, apps/proxy-chain/src/multiChainBridgeClient.ts, package.json, packages/blocks/src/blocks/blockManager.ts, packages/blocks/src/events/eventManager.ts, packages/blocks/src/events/types.ts, packages/clients/src/index.ts, packages/clients/src/networkClient.ts, packages/clients/src/types.ts, packages/clients/src/wormholeClient.ts, packages/graphql/src/fragments/actions.graphql, packages/graphql/src/generated.ts, packages/graphql/src/queries/action.graphql, pnpm-lock.yaml
This PR solves adding the new `ColonyActionType.AddProxyColony` action to DB on the main chain block ingestor, while also updating the action's `multiChainInfo` on the proxy chain block ingestor based on the data retrieved from the mocked `Wormhole` endpoint - this endpoint offers info about the deployment status on the requested proxy chain.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3863)
- Create the new action type `ColonyActionType.AddProxyColony` in the DB
- Added a new `WormholeClient` in the shared `clients` package
- Add multi-transaction processing for the proxy colony and wormhole events
=> [Proxy colonies] Feat: Get the main-chain transaction hash from a proxy chain 

src/handlers/actions/makeArbitraryTransaction.ts, src/handlers/motions/motionCreated/handlers/makeArbitraryTransactions.ts
This PR is cover https://github.com/JoinColony/colonyCDapp/issues/3536  and could be tested in scope of https://github.com/JoinColony/colonyCDapp/pull/3933
=> feat: handle arbitrary transaction motion

package-lock.json, package.json, src/handlers/reputationMiningCycle/reputationMiningCycleComplete.ts
This PR fixes the timestamp value for the `reputationMiningCycle` handler, since if the ingestor falls behind the chain, by the time it catches back up to this event it will have used the wrong timestamp for reputation, meaning both updates and UI reporting will be wrong.
This value is mostly used for UI display purposes, however, even so, if it gets out of date, users might get the wrong impression when looking up the reputation cycle's next update in the user hub
=> Fix Reputation Mining Cycle Handler Timestamp

apps/main-chain/src/handlers/colonies/colonyAdded.ts, apps/main-chain/src/handlers/colonies/helpers/createUniqueColony.ts, apps/main-chain/src/handlers/colonies/helpers/validateCreationSalt.ts, apps/main-chain/src/utils/transactions.ts, packages/graphql/src/generated.ts
This PR addresses adding the colony create event details to the `Colony` model upon colony creation.
This information is needed for easily deploying new Proxy Colonies.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3920)
[Scripts PR](https://github.com/JoinColony/cdapp-scripts/pull/1)
=> [Proxy colonies] Feat: Add create event details to colony model

apps/main-chain/src/handlers/metadataDelta/metadataDelta.ts, apps/main-chain/src/handlers/motions/motionCreated/handlers/metadataDelta.ts, apps/main-chain/src/handlers/motions/motionCreated/motionCreated.ts, packages/graphql/src/generated.ts
These changes should allow the enabling and disabling of Proxy Colonies via the Reputation decision method.
Please test this with [colonyCDapp PR #4063: Feat: Enable and Disable Proxy Colonies via the Reputation Motion ](https://github.com/JoinColony/colonyCDapp/pull/4063)
=> Feat: Enable and Disable Proxy Colonies via the Reputation Motion

apps/main-chain/src/handlers/multiSig/multiSigCreated/handlers/metadataDelta.ts, packages/graphql/src/generated.ts
These changes should allow the enabling and disabling of Proxy Colonies via the Multi-Sig decision method.
Please test this with [colonyCDapp PR #4079: Feat: Enable and Disable Proxy Colonies via Multi-Sig ](https://github.com/JoinColony/colonyCDapp/pull/4079)
=> Feat: Enable and Disable Proxy Colonies via Multi-Sig

apps/main-chain/src/eventListeners/network.ts, apps/main-chain/src/eventListeners/proxyColonies.ts, apps/proxy-chain/src/eventListeners/network.ts, apps/proxy-chain/src/eventListeners/proxyColonies.ts
Due to the fact both `CHAIN_CONTRACT_ADDRESS` and `CHAIN_NETWORK_CONTRACT` should point to the same value, given the `CHAIN_NETWORK_CONTRACT` is already setup in the dApp, I have removed the `CHAIN_CONTRACT_ADDRESS`.
The only impact is for the `addNetworkEventListener` and `addProxyColoniesEventListener` utilities that will now add the listeners for the given network contract address.
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/4136)
=> [Proxy colonies M0] Align CHAIN_NETWORK_CONTRACT and CHAIN_CONTRACT_ADDRESS on block ingestor
